//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoutingServer.ProxyCacheReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyGeoCoordinate", Namespace="http://schemas.datacontract.org/2004/07/ProxyCacheServer")]
    [System.SerializableAttribute()]
    public partial class MyGeoCoordinate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LongitudeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RouteInfo", Namespace="http://schemas.datacontract.org/2004/07/ProxyCacheServer")]
    [System.SerializableAttribute()]
    public partial class RouteInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double DistanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double DurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GeometryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RoutingServer.ProxyCacheReference.RouteInstruction[] InstructionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProfileField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Distance {
            get {
                return this.DistanceField;
            }
            set {
                if ((this.DistanceField.Equals(value) != true)) {
                    this.DistanceField = value;
                    this.RaisePropertyChanged("Distance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((this.DurationField.Equals(value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Geometry {
            get {
                return this.GeometryField;
            }
            set {
                if ((object.ReferenceEquals(this.GeometryField, value) != true)) {
                    this.GeometryField = value;
                    this.RaisePropertyChanged("Geometry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RoutingServer.ProxyCacheReference.RouteInstruction[] Instructions {
            get {
                return this.InstructionsField;
            }
            set {
                if ((object.ReferenceEquals(this.InstructionsField, value) != true)) {
                    this.InstructionsField = value;
                    this.RaisePropertyChanged("Instructions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Profile {
            get {
                return this.ProfileField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfileField, value) != true)) {
                    this.ProfileField = value;
                    this.RaisePropertyChanged("Profile");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RouteInstruction", Namespace="http://schemas.datacontract.org/2004/07/ProxyCacheServer")]
    [System.SerializableAttribute()]
    public partial class RouteInstruction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double DistanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Distance {
            get {
                return this.DistanceField;
            }
            set {
                if ((this.DistanceField.Equals(value) != true)) {
                    this.DistanceField = value;
                    this.RaisePropertyChanged("Distance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyContract", Namespace="http://schemas.datacontract.org/2004/07/ProxyCacheServer")]
    [System.SerializableAttribute()]
    public partial class MyContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] citiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string commercial_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string country_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] cities {
            get {
                return this.citiesField;
            }
            set {
                if ((object.ReferenceEquals(this.citiesField, value) != true)) {
                    this.citiesField = value;
                    this.RaisePropertyChanged("cities");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string commercial_name {
            get {
                return this.commercial_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.commercial_nameField, value) != true)) {
                    this.commercial_nameField = value;
                    this.RaisePropertyChanged("commercial_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string country_code {
            get {
                return this.country_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.country_codeField, value) != true)) {
                    this.country_codeField = value;
                    this.RaisePropertyChanged("country_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyCacheReference.IProxyCacheService")]
    public interface IProxyCacheService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyCacheService/GetStationsForContract", ReplyAction="http://tempuri.org/IProxyCacheService/GetStationsForContractResponse")]
        string GetStationsForContract(string contract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyCacheService/GetStationsForContract", ReplyAction="http://tempuri.org/IProxyCacheService/GetStationsForContractResponse")]
        System.Threading.Tasks.Task<string> GetStationsForContractAsync(string contract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyCacheService/GetCoordinates", ReplyAction="http://tempuri.org/IProxyCacheService/GetCoordinatesResponse")]
        RoutingServer.ProxyCacheReference.MyGeoCoordinate GetCoordinates(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyCacheService/GetCoordinates", ReplyAction="http://tempuri.org/IProxyCacheService/GetCoordinatesResponse")]
        System.Threading.Tasks.Task<RoutingServer.ProxyCacheReference.MyGeoCoordinate> GetCoordinatesAsync(string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyCacheService/GetRouteInfo", ReplyAction="http://tempuri.org/IProxyCacheService/GetRouteInfoResponse")]
        RoutingServer.ProxyCacheReference.RouteInfo GetRouteInfo(RoutingServer.ProxyCacheReference.MyGeoCoordinate start, RoutingServer.ProxyCacheReference.MyGeoCoordinate end, string profile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyCacheService/GetRouteInfo", ReplyAction="http://tempuri.org/IProxyCacheService/GetRouteInfoResponse")]
        System.Threading.Tasks.Task<RoutingServer.ProxyCacheReference.RouteInfo> GetRouteInfoAsync(RoutingServer.ProxyCacheReference.MyGeoCoordinate start, RoutingServer.ProxyCacheReference.MyGeoCoordinate end, string profile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyCacheService/GetAllStations", ReplyAction="http://tempuri.org/IProxyCacheService/GetAllStationsResponse")]
        string GetAllStations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyCacheService/GetAllStations", ReplyAction="http://tempuri.org/IProxyCacheService/GetAllStationsResponse")]
        System.Threading.Tasks.Task<string> GetAllStationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyCacheService/GetContracts", ReplyAction="http://tempuri.org/IProxyCacheService/GetContractsResponse")]
        RoutingServer.ProxyCacheReference.MyContract[] GetContracts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyCacheService/GetContracts", ReplyAction="http://tempuri.org/IProxyCacheService/GetContractsResponse")]
        System.Threading.Tasks.Task<RoutingServer.ProxyCacheReference.MyContract[]> GetContractsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyCacheService/GetCityFromCoordinates", ReplyAction="http://tempuri.org/IProxyCacheService/GetCityFromCoordinatesResponse")]
        string GetCityFromCoordinates(RoutingServer.ProxyCacheReference.MyGeoCoordinate coord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyCacheService/GetCityFromCoordinates", ReplyAction="http://tempuri.org/IProxyCacheService/GetCityFromCoordinatesResponse")]
        System.Threading.Tasks.Task<string> GetCityFromCoordinatesAsync(RoutingServer.ProxyCacheReference.MyGeoCoordinate coord);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProxyCacheServiceChannel : RoutingServer.ProxyCacheReference.IProxyCacheService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProxyCacheServiceClient : System.ServiceModel.ClientBase<RoutingServer.ProxyCacheReference.IProxyCacheService>, RoutingServer.ProxyCacheReference.IProxyCacheService {
        
        public ProxyCacheServiceClient() {
        }
        
        public ProxyCacheServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProxyCacheServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProxyCacheServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProxyCacheServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetStationsForContract(string contract) {
            return base.Channel.GetStationsForContract(contract);
        }
        
        public System.Threading.Tasks.Task<string> GetStationsForContractAsync(string contract) {
            return base.Channel.GetStationsForContractAsync(contract);
        }
        
        public RoutingServer.ProxyCacheReference.MyGeoCoordinate GetCoordinates(string address) {
            return base.Channel.GetCoordinates(address);
        }
        
        public System.Threading.Tasks.Task<RoutingServer.ProxyCacheReference.MyGeoCoordinate> GetCoordinatesAsync(string address) {
            return base.Channel.GetCoordinatesAsync(address);
        }
        
        public RoutingServer.ProxyCacheReference.RouteInfo GetRouteInfo(RoutingServer.ProxyCacheReference.MyGeoCoordinate start, RoutingServer.ProxyCacheReference.MyGeoCoordinate end, string profile) {
            return base.Channel.GetRouteInfo(start, end, profile);
        }
        
        public System.Threading.Tasks.Task<RoutingServer.ProxyCacheReference.RouteInfo> GetRouteInfoAsync(RoutingServer.ProxyCacheReference.MyGeoCoordinate start, RoutingServer.ProxyCacheReference.MyGeoCoordinate end, string profile) {
            return base.Channel.GetRouteInfoAsync(start, end, profile);
        }
        
        public string GetAllStations() {
            return base.Channel.GetAllStations();
        }
        
        public System.Threading.Tasks.Task<string> GetAllStationsAsync() {
            return base.Channel.GetAllStationsAsync();
        }
        
        public RoutingServer.ProxyCacheReference.MyContract[] GetContracts() {
            return base.Channel.GetContracts();
        }
        
        public System.Threading.Tasks.Task<RoutingServer.ProxyCacheReference.MyContract[]> GetContractsAsync() {
            return base.Channel.GetContractsAsync();
        }
        
        public string GetCityFromCoordinates(RoutingServer.ProxyCacheReference.MyGeoCoordinate coord) {
            return base.Channel.GetCityFromCoordinates(coord);
        }
        
        public System.Threading.Tasks.Task<string> GetCityFromCoordinatesAsync(RoutingServer.ProxyCacheReference.MyGeoCoordinate coord) {
            return base.Channel.GetCityFromCoordinatesAsync(coord);
        }
    }
}
