@ECHO OFF
TITLE Lancement des serveurs

ECHO Lancement du ProxyCacheServer (SOAP)...
START "ProxyCacheServer (SOAP)" "%~dp0LetsGoBiking\ProxyCacheServ\bin\Debug\ProxyCacheServ.exe"

ECHO Lancement du RoutingServer (REST)...
START "RoutingServer (REST)" "%~dp0LetsGoBiking\RoutingServer\bin\Debug\RoutingServer.exe"

ECHO Lancement du NotificationService...
START "NotificationService" "%~dp0LetsGoBiking\NotificationService\bin\Debug\NotificationService.exe"

ECHO Lancement du Client Lourd...
START "HeavyClient" "%~dp0LetsGoBiking\HeavyClient\bin\Debug\HeavyClient.exe"

ECHO Demarrage en cours...